import { Fragment, useRef, useState } from 'react';
import Head from 'next/head';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/Hey.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import projet1 from '../public/projet1.png';
import projet2 from '../public/projet2.png';
import ModalProjet1 from '../Components/ModalProjet1';

export default function Home() {
  const [openProjet1, setOpenProjet1] = useState(false);
  const [description, setDescription] = useState(null);

  return (
    <div>
      <Head>
        <title>Nesrine Hadboun Portfolio</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <ModalProjet1
        openProjet1={openProjet1}
        setOpenProjet1={setOpenProjet1}
        description={description}
        setDescription={setDescription}
      />
      <main className='bg-white px-10  md:px-20 lg:px-40'>
        <section className=' min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons text-shamrock'>
              Portfolio
            </h1>
            <ul className=' flex items-center'>
              <li>
                <a
                  className='bg-gradient-to-r from-asparagus to-shamrock text-white px-4 py-2 rounded ml-8'
                  href='#'
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10 py-10'>
            <h2 className=' text-5xl py-2 text-indian font-medium md:text-6xl'>
              Nesrine Hadboun
            </h2>
            <h3 className='text-2xl py-2 md:text-3xl'>
              Frontend Developer.
            </h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto'>
              Hello! Im a web developer focused on building beautiful
              interfaces & experiences. Previously, I have done
              various jobs such as perfumery saleswoman, esthetician
              or tramway driver! All this professional experience
              allowed me to forge myself and to find today a job that
              really motivates me!
            </p>
            <p>Get in touch 👉🏼 Nesrine.hadboun@live.fr</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-ecru'>
            <a href='https://twitter.com/Codes_ness'>
              <AiFillTwitterCircle />
            </a>
            <a href='https://www.linkedin.com/in/nesrine-hadboun-84b7054b/'>
              <AiFillLinkedin />
            </a>
            <a href='https://github.com/Nesrinemh'>
              <AiFillGithub />
            </a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-indian rounded-full w-80 h-80 mt-20 overflow-hidden  md:h-96 md:w-96'>
            <Image
              src={deved}
              layout='fill'
              objectFit='cover'
              alt='profil'
            />
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-3'>Skills</h3>
            <p className='text-md leading-8 text-gray-800'>
              <p className='text-md leading-8 text-gray-80'>
                Here are in a few words the skills I acquired during
                my last training with{' '}
                <span className='text-shamrock'>
                  Scrimba Bootcamp{' '}
                </span>{' '}
                as well as other skills where I am currently training.
              </p>
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center    shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <div className='flex justify-center'>
                <Image src={design} width={100} height={100} />
              </div>
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Beautiful Designs
              </h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs design
                theory.
              </p>
              <h4 className='py-4 text-shamrock'>
                Design tools I use
              </h4>
              <p className='text-gray-800 py-1'>CSS</p>
              <p className='text-gray-800 py-1'>Tailwind</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div className='text-center    shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <div className='flex justify-center'>
                <Image src={code} width={100} height={100} />
              </div>
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Technologies
              </h3>
              <p className='py-2'>
                Using latest technologies to create
              </p>
              <h4 className='py-4  text-shamrock'>Techno I use</h4>
              <p className='text-gray-800 py-1'>Javascript</p>
              <p className='text-gray-800 py-1'>React</p>
              <p className='text-gray-800 py-1'>Next.js</p>
            </div>
            <div className='text-center    shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <div className='flex justify-center'>
                <Image src={consulting} width={100} height={100} />
              </div>
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Dev environment
              </h3>
              <p className='py-2'>
                Tools that allow me to optimize my work and
                collaborate.
              </p>
              <h4 className='py-4  text-shamrock'>Daily tools</h4>
              <p className='text-gray-800 py-1'>Github</p>
              <p className='text-gray-800 py-1'>Vercel</p>
              <p className='text-gray-800 py-1'>VS Code</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 mb-8'>
              Some Things I’ve Built
            </h3>
          </div>
          <div className='flex flex-col gap-10 lg:flex-row lg:flex-wrap '>
            <div className='basis-1/3 flex-1'>
              <Image
                src={projet1}
                className='rounded-lg cursor-pointer  object-cover '
                width={'100%'}
                height={'100%'}
                layout='responsive'
                onClick={() => {
                  setOpenProjet1(true),
                    setDescription(
                      'This project of movies API was made with Next.JS 13 & Tailwind CSS. You can click on view project to test or cancel.'
                    );
                }}
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                src={projet2}
                className='rounded-lg object-cover '
                width={'100%'}
                height={'100%'}
                layout='responsive'
                onClick={() => {
                  setOpenProjet1(true),
                    setDescription(
                      'This project of movies API was made with Next.JS 13 & Tailwind CSS. You can click on view project to test or cancel.'
                    );
                }}
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                src={web3}
                className='rounded-lg object-cover '
                width={'100%'}
                height={'100%'}
                layout='responsive'
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                src={web4}
                className='rounded-lg object-cover '
                width={'100%'}
                height={'100%'}
                layout='responsive'
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                src={web5}
                className='rounded-lg  object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive'
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                src={web6}
                className='rounded-lg  object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive'
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
